### ISSUE TITLE
Docker volume driver doesn't seem to work for EC2

### ISSUE THREAD

**Issue by sehyoc** [emccode/rexray#133]
Trying to use rexray for Docker volume driver generates following error:

`Error response from daemon: Plugin Error: {"Error":"Error: Driver Instance discovery failed: AWS was not able to validate the provided access credentials (AuthFailure)"}`

I use following docker command:

`sudo docker run --volume-driver=rexray \
     -e AWS_ACCESS_KEY=[key] \
     -e  AWS_SECRET_KEY=[value] \
     -e REXRAY_STORAGEDRIVERS=ec2 \
     -v test:/test  busybox sh `

I also tried putting environment variable and putting in config.yml.

Here is log output

`Binary: /usr/bin/rexray
SemVer: 0.2.0
OsArch: Linux-x86_64
Branch: v0.2.0
Commit: b018a3be05b54a110728d3669213e3d8f65de197
Formed: Wed, 30 Sep 2015 21:29:02 UTC

time="2015-10-18T19:08:47Z" level=info msg="dialing /tmp/WiGAiPCsyFiyZqbngsgbDQLQPMXwcQCS.sock" 
time="2015-10-18T19:08:47Z" level=info msg="created pid file, pid=2257" 
time="2015-10-18T19:08:47Z" level=info msg="initialized module instance" address="tcp://:7979" id=1 ignoreFailOnInit=false typeId=1 typeName=AdminModule 
time="2015-10-18T19:08:47Z" level=info msg="initialized module instance" address="unix:///run/docker/plugins/rexray-remote.sock" id=2 ignoreFailOnInit=tr
ue typeId=2 typeName=DockerRemoteVolumeDriverModule 
time="2015-10-18T19:08:47Z" level=info msg="initialized module instance" address="unix:///run/docker/plugins/rexray.sock" id=3 ignoreFailOnInit=true type
Id=3 typeName=DockerVolumeDriverModule 
time="2015-10-18T19:08:47Z" level=info msg="started module" address="tcp://:7979" id=1 typeId=1 typeName=AdminModule 
time="2015-10-18T19:08:47Z" level=info msg="started module" address="unix:///run/docker/plugins/rexray-remote.sock" id=2 typeId=2 typeName=DockerRemoteVo
lumeDriverModule 
time="2015-10-18T19:08:47Z" level=info msg="started module" address="unix:///run/docker/plugins/rexray.sock" id=3 typeId=3 typeName=DockerVolumeDriverMod
ule 
time="2015-10-18T19:08:47Z" level=info msg="service sent registered modules start signals" 
time="2015-10-18T19:08:47Z" level=info msg="service successfully initialized, waiting on stop signal" 
time="2015-10-18T19:08:53Z" level=info msg="create volume" driverName=docker volumeName=test volumeOpts=map[] 
time="2015-10-18T19:08:53Z" level=info msg="creating volume" driverName=docker volumeName=test volumeOpts=map[] 
time="2015-10-18T19:08:53Z" level=error msg="/VolumeDriver.Create: error creating volume" error="Error: Driver Instance discovery failed: AWS was not abl
e to validate the provided access credentials (AuthFailure)" 
`

**Comment by clintonskitson** [comment]
@sehyoc In order to troubleshoot this there are a couple of steps I want to make sure you are doing in order.

The step in getting RR running is to configure your environment variables.  Once this happens correctly, you should be able to run `rexray volume` without error.  If there are errors, you can add a `-l debug` to review the errors.  This represents one way of running RR, but you likely did an `export` of the env variables here.  But, this is a good test though since you know RR is functioning with the information you provided.

The step represents running RR in interactive mode as a CLI.  If you want it running as a daemon to service Docker plugin requests, then it is best to configure the variables in a YAML file (but is optional).

Typically you would save your configuration in a `/etc/rexray/config.yml` file similar to the following.
```
StorageDrivers: 
  - ec2
AwsAccessKey: accessKey
AwsSecretKey: secretKey
```

Now if you perform a `rexray start` then it will start the daemon for RR which serves Docker requests.  

I am assuming your situation is happening because a) the RR daemon started before you configured your user/pass b) the env variables aren't available to the RR service.

**Comment by clintonskitson** [comment]
@sehyoc Can we consider this resolved?  If so can you close the comment?  Thanks
