### ISSUE TITLE
Existing RR binary conflict causes error during install

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#151]
It would be nice to ensure that when a RR install occurs, that it forces the overwrite of an existing RR binary.

```
[root@mdm1 centos]# curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s unstable latest  -
	file /usr/bin/rexray from install of rexray-0.2.1+rc1+2-1.x86_64 conflicts with file from package rexray-0.2.1+dev+49-1.x86_64
```

**Comment by clintonskitson** [comment]
I wonder if this is regarding downgrades?

**Comment by clintonskitson** [comment]
for RPM? `--replacefiles                   ignore file conflicts between packages`

**Comment by akutz** [comment]
Hi @clintonskitson,

This is a non-issue that's an issue. It has to do with the addition of the `dev` bits to the version. I'll have to investigate how to handle upgrades with RPMs and DEBs when versions have qualifiers in them.

**Comment by akutz** [comment]
This is a not a bug as it's dependent upon the version scheme we've elected to use. I wanted to avoid placing a version number in the product until we reach said version number, but you wanted us to note the *target* version instead of the number of builds since the previous, tagged release. RPMs don't like it when we go from "+dev" to "+rc" as the RPM manager has no notion that it's an upgrade path. Additionally, this is an issue only encountered by people using unstable builds, and the installer is not guaranteed to work between anything but stable releases.

**Comment by clintonskitson** [comment]
Agreed here, let's review the releases with @codenrhoden at a future point.
