### ISSUE TITLE
scaleio driver: volumes are not allowed multimap

### ISSUE THREAD

**Issue by bottkars** [emccode/rexray#282]
in a mesos conainerizer environemnt, failover fails as scaleio volumes are not exposed using allowmultimap to the initial sdc

**Comment by clintonskitson** [comment]
@bottkars There is a configurable parameter for `preemption` that would cover this [here](http://rexray.readthedocs.org/en/stable/user-guide/config/).

There are lots of failure scenarios to cover here.  In the case of a volume being requested for any reason by another host, the pre-emption feature will enable that requesting host to take control of the volume forcefully and remote the access from the existing host.  It sounds like you need to enable this feature to get the functionality you are expecting.  Otherwise the volume must be unmounted properly before it is requested by another host.

**Comment by bottkars** [comment]
ok, will check that. thought preemtion is only doing the OS unmaount, if it also do the disconnect i am fine

**Comment by clintonskitson** [comment]
Yes it is the whole workflow.

`Host 1` owns volume, `Host 2` requests it with pre-emption enabled, `Host 2` initiates forced detach from `Host 1`, `Host 2` attaches to himself...

**Comment by bottkars** [comment]
Great! Checked into my cookbook and will Test tonite
