### ISSUE TITLE
Always load env vars in /etc/environment if present

### ISSUE THREAD

**Issue by akutz** [emccode/rexray#40]
Because `sudo` doesn't always play nice with `/etc/environment` and so many people place configuration information there even when inappropriate or not fully understood, `REX-Ray` should manually load `/etc/environment` in order to relieve users of possible issues due to Linux systems being so disparate and supporting so many different configuration options.

**Comment by akutz** [comment]
Hi @kacole2,

I filed this issue for you.

**Comment by akutz** [comment]
Closed with PR #41

**Comment by clintonskitson** [comment]
@akutz I just ran into a problem here because of the setting.  I was trying to specify a different `REXRAY_STORAGEDRIVERS` via an env on the CLI.  It took me a bit to realize that the `/etc/environment` was overriding anything I specifically set before running.  Although this setting does ensure one doesn't need to use `sudo su`, IMO it might cause some unexpected results for those familiar with env settings.  If our best practice is to begin using configuration files where possible, do we still think this setting is relevant?

**Comment by akutz** [comment]
Hi @clintonskitson,

This is also easily fixed by checking to see if an environment variable is already defined. This is my preferred fix as just the other day @jonasrosland pushed some new article/blog/info using `/etc/environment` despite the fact that that we've been pushing config files for a few weeks. This isn't to come down on @jonasrosland :), but rather to say that I don't wish to break existing methods that are so commonly used and only recently documented.

Thoughts?

I'll do either here, I just wanted to throw the above out there.

**Comment by akutz** [comment]
Hi @clintonskitson,

Any thoughts? Otherwise I'll update it as I mentioned above.

**Comment by clintonskitson** [comment]
I'm ok with this.  Let's just make sure the configuration priority is called out in the README.

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm not sure we have to call it out with regards to *this* as it will fall back in line with the standard Viper order. However, yes, we should call that out.

**Comment by akutz** [comment]
Hi @clintonskitson,

PR #72 will handle this issue. As for the documentation, please create a documentation issue so we can start using that to track all of the documentation requests/updates we need to handle.
