### ISSUE TITLE
Handle phantom mounts on certain EC2 instance types

### ISSUE THREAD

**Issue by raphtheb** [emccode/rexray#410]
Hello! Was asked to capture my findings into an issue on the slack channel.

Starting a few months ago i had some issues regarding this specific error message, using a CoreOS AMI on aws.
```
docker run -ti --security-opt=label:disable --volume-driver=rexray -v testvolume:/tmp --name containerman busybox
docker: Error response from daemon: VolumeDriver.Mount: {"Error":"InvalidParameterValue: Invalid value '/dev/xvdb' for unixDevice. Attachment point /dev/xvdb is already in use
    status code: 400, request id: 5eeabc8e-38c2-4e2a-b948-e0f5fa8d986e"}.
See 'docker run --help'.
```

After quite a lot of digging, i believe i’ve found that the root cause is the "phantom" mount of ephemeral devices on certain EC2 instance types. The bottom of [this document ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html?icmpid=docs_ec2_console )briefly touches on it. As you can see, from my test instance, there is no OS-visible xvdb device:

```
$ sudo ls /dev/xv*
/dev/xvda   /dev/xvda2	/dev/xvda4  /dev/xvda7
/dev/xvda1  /dev/xvda3	/dev/xvda6  /dev/xvda9
```
However, when i poll the AWS api from that very same test instance:

```
curl http://169.254.169.254/latest/meta-data/block-device-mapping/
ami
ephemeral0
root

curl http://169.254.169.254/latest/meta-data/block-device-mapping/ami
/dev/xvda

curl http://169.254.169.254/latest/meta-data/block-device-mapping/ephemeral0
xvdb
```

So it appears that this xvdb device really does exist, but isn’t visible from the OS somehow. That apparently causes rex-ray to try and attach EBS volumes to this mount point (seemingly the first available one). It then fails to mount, and returns the error message straight from the AWS API.

 I wonder if there’s a way rex-ray (or libstorage now?) can either:

- Look out for those hidden volumes and ignore them, thus resolving the problem.
- Lets you customize the value of first "available" mount device to use. (Say, start from /dev/xvdf or /dev/sdf)

Cheers!

**Comment by clintonskitson** [comment]
Thank you for filing this @raphtheb, we will definitely add this to the list for the EC2 driver.

**Comment by feniix** [comment]
@raphtheb I found a workaround see: https://github.com/emccode/rexray/issues/425#issuecomment-223630227

**Comment by alexandrst88** [comment]
@clintonskitson  any updates?

**Comment by akutz** [comment]
Closed with #578

**Comment by akutz** [comment]
Hi @alexandrst88,

Specifically it's [this update](https://github.com/emccode/libstorage/blob/master/drivers/storage/ebs/utils/utils_unix.go#L9-L18) to the new EBS (formerly EC2) driver that should prevent these phantom mounts. The new EBS driver begins next device assignment at `xvdf`.

**Comment by akutz** [comment]
By the way, as @cduchesne was surprised, the new restriction makes only 10 devices available for EC2 instances using the EBS driver. This is due to Amazon's [recommended EBS restrictions](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html). We're discussing making the range configurable to accommodate for greater than 10 devices.

**Comment by bosschaert** [comment]
The fix in https://github.com/codedellemc/libstorage/blob/master/drivers/storage/ebs/utils/utils_unix.go#L9-L18 looks a bit random to me. For example I have to work with EC2 VMs that end up having 22 phantom ephemeral drives which occupy all the drive letters from xvdb to xvdx, so that fix won't work with my VMs. Would it be possible to use a set of drive mounts instead that don't interfere with others, e.g. /dev/rexray1, /dev/rexray2 and so on?
