### ISSUE TITLE
Too many open files in rexray logs

### ISSUE THREAD

**Issue by CBR09** [emccode/rexray#441]
Hi,
I saw this issue at #291, and in docker 1.10.3 seem to fix with PR https://github.com/docker/docker/pull/20686

But I still have similar issue when using docker 1.10.3 with rexray 0.3.3

> root@Ubuntu2:~# uname -a
> Linux Ubuntu2 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> root@Ubuntu2:~# docker -v
> Docker version 1.10.3, build 20f81dd
> root@Ubuntu2:~# rexray version
> DEBU[0000] updated log level                             logLevel=debug
> Binary: /usr/bin/rexray
> SemVer: 0.3.3
> OsArch: Linux-x86_64
> Branch: v0.3.3
> Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
> Formed: Fri, 22 Apr 2016 02:41:36 ICT
> root@Ubuntu2:~# docker volume ls; lsof | grep rexray.sock | wc -l
> DRIVER              VOLUME NAME
> local               0bb337a4e657cb097dd2efca29e29b49f25eb526a874004e429971d201a55351
> local               4b08bf71fdca7f50fe91a5dede46231e4adf012e26cb7d754dffa5d28653905e
> rexray              tata
> rexray              toi
> rexray              hehe
> rexray              test
> rexray              RancherOSv4.4_Data
> 240
> root@Ubuntu2:~# docker volume ls; lsof | grep rexray.sock | wc -l
> DRIVER              VOLUME NAME
> local               0bb337a4e657cb097dd2efca29e29b49f25eb526a874004e429971d201a55351
> local               4b08bf71fdca7f50fe91a5dede46231e4adf012e26cb7d754dffa5d28653905e
> rexray              tata
> rexray              toi
> rexray              hehe
> rexray              test
> rexray              RancherOSv4.4_Data
> 252
> root@Ubuntu2:~# docker volume ls; lsof | grep rexray.sock | wc -l
> DRIVER              VOLUME NAME
> local               0bb337a4e657cb097dd2efca29e29b49f25eb526a874004e429971d201a55351
> local               4b08bf71fdca7f50fe91a5dede46231e4adf012e26cb7d754dffa5d28653905e
> rexray              tata
> rexray              toi
> rexray              hehe
> rexray              test
> rexray              RancherOSv4.4_Data
> 264
> 

Logs:

> time="2016-05-26T14:05:11+07:00" level=error msg="error getting driver instance" inner.inner.Op=Get inner.provider=Openstack inner.moduleName=default-docker inner.inner.Err.Op=dial inner.inner.Err.Net=tcp inner.inner.Err.Source=<nil> inner.inner.Err.Err.Syscall=socket inner.inner.Err.Err.Err="too many open files" inner.inner.Err.Addr.Zone= inner.inner.Err.Addr.IP=10.76.0.2 inner.inner.Err.Addr.Port=8774 inner.inner.URL="http://10.76.0.2:8774/v2/630cebab9292487db8baecb72c86f825/servers/c35ba858-bc5e-4f11-9952-fb2d16cd4501" moduleName=default-docker provider=Openstack

Thanks

**Comment by akutz** [comment]
Hi @CBR09 , Hi @kacole2,

So this is likely fixed in RR 0.4.0, because libStorage ran into a similar issue that I corrected with [this solution](https://github.com/emccode/libstorage/blob/master/drivers/storage/libstorage/libstorage_driver.go#L58-L72). 

You may or may not be aware, but on a UNIX-based system, almost everything is a "file", even TCP sockets. That's why on Linux or Darwin you can execute the following command to see which TCP ports are open:

```
$ sudo lsof -noP | grep LISTEN
vpnagentd    54            root    5u     IPv4 0xf3d0852df6767881        0t0       TCP 127.0.0.1:29754 (LISTEN)
ciscod       55            root    3u     IPv4 0xf3d0852df6768a91        0t0       TCP 127.0.0.1:1023 (LISTEN)
iTunes    27099           akutz   31u     IPv4 0xf3d0852e13fe2881        0t0       TCP *:53365 (LISTEN)
```

The `lsof` command simply _lists open files_, hence the name. So the error you're seeing above is to do with the REX-Ray HTTP client. By default in Go >=1.6, the HTTP connections are not closed in order to be reused. However, this can quickly exhaust the number of open files available to the OS. You can either increase this number for [Linux](http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/) or [Darwin](https://www.freebsd.org/doc/handbook/configtuning-kernel-limits.html), or, what you should do, is disable the keep alive functionality in the HTTP client.

That is what I did with the libStorage client. During testing I was exhausting a process's number of open file allocation, so I enabled the HTTP transport's `DisableKeepAlive` option. This [is the same](http://craigwickesser.com/2015/01/golang-http-to-many-open-files/) as setting the `Close` field to `true` for an HTTP request in Go. 

This problem is likely fixed in 0.4, but if you want to know how to fix it now with a patch, please feel free to compile RR yourself with this option.

**Comment by clintonskitson** [comment]
Thanks for this @akutz. Although related it is aligned to RR 0.3.3. There
problem there is on Docker's side which is fixed in 1.11.0 which is past
the version reported here.

**Comment by akutz** [comment]
Ah, cool. Yeah, I assumed it was the RR client, but I guess like you said it was Docker.

**Comment by CBR09** [comment]
Thanks @akutz, @clintonskitson for your attention. So to fix this issue, I need to upgrade to docker 1.11.0 or compile docker 1.10.0 with this https://github.com/docker/docker/pull/20686.

**Comment by clintonskitson** [comment]
Correct @CBR09

**Comment by CBR09** [comment]
Thanks @clintonskitson
