### ISSUE TITLE
Deprecate docker spec file

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#451]
The spec file that is created based on the Docker Volume Driver is no longer needed. This was initially implemented to follow the defined spec which since has been updated.

Docker looks up UNIX sockets first by name. If those don't exist then it turns to the spec file to review. This spec file would then only include a HTTP/IP endpoint. Since RR only is addressed by Docker locally, there is no need to populate a spec file and only adds complexity and timeouts to occur when the spec file exists when it shouldn't.

https://github.com/emccode/rexray/blob/master/daemon/module/docker/volumedriver/voldriver.go#L173-L181

**Comment by Oskoss** [comment]
@clintonskitson Question for you guys. This broke our code I noticed that you said

> Since RR only is addressed by Docker locally

We use a separate volume manager for CloudFoundry and were using the RR docker volume plugins to manage multiple storage arrays. Is there any reason *not* to have this extra feature still in RR? As a work around we can still create our own spec files.

**Comment by akutz** [comment]
I actually brought up your team as an objection to this, but ultimately Clint convinced me to remove it because he noted that if Docker detects both a local UNIX socket *and* a spec file that points to said UNIX socket, the overall performance is severely impacted as Docker will scan both as endpoints for volumes.

I agreed that the use case was an edge case and we'd simply document how to create the spec file manually and the caveats said spec file would entail.

We did consider continuing to create the spec file for TCP endpoints alone.

Thoughts?

**Comment by akutz** [comment]
By the way @Oskoss. How large of a deployment issue is this for your side. Does it cause a wide-spread issue to have to create the spec file manually? We're attempting to gauge the size of the problem this causes you. Our concern is the security implementation of exposing the Docker endpoint remotely. Now that we support distributed REX-Ray, the need for a remote Docker endpoint is basically absent except for edge cases such as yours. In such an environment we elected to remove a possible attack vector.

**Comment by Oskoss** [comment]
@akutz Gotcha, I just changed around my rexray bosh deployment (whenever a CloudFoundry Admin tries to use EMC storage with CloudFoundry they use it!) to manually create the spec file. In essence a bosh deployment is a big script that deploys rexray and monitors it to make sure its running. Its not too big of a deal, just was super convenient to have and much prettier in golang rather than bash. I could put together a PR that would autogen a spec file only if the endpoint were to be defined as a tcp:// endpoint *NOT* a unix:// endpoint.

What do you think?
