### ISSUE TITLE
Service selector not working

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#464]
The service selector `-s` flag does not seem to be working. There are multiple services defined, but the first service seems to be the one being returned each time.

See the gist https://gist.github.com/clintonskitson/7726774770cc5e49f40f8fca3365c4f2

```
rexray version
REX-Ray
-------
Binary: /go/bin/rexray
SemVer: 0.4.0-rc4+12
OsArch: Linux-x86_64
Branch: feature/doc_updates
Commit: 0aca40ba1b01ebccb4706b6dd787a7f3d5420a02
Formed: Fri, 17 Jun 2016 01:56:43 UTC

libStorage
----------
SemVer: 0.1.3
OsArch: Linux-x86_64
Branch: v0.1.3
Commit: 182a626937677a081b89651598ee2eac839308e7
Formed: Thu, 16 Jun 2016 20:30:30 UTC
```

**Comment by akutz** [comment]
Hi @clintonskitson,

I spent far too long setting things up to replicate this before looking at the command you were executing. It's part and parcel of the exact same issue we spent most of yesterday and this evening discussing via Slack regarding the scope of the definition of properties under `rexray` and the scoping of `rexray.modules.default-docker`. I mentioned I removed that. It's up to you to pull down those changes. I know you have not, because if you see [the logs](https://gist.github.com/clintonskitson/7726774770cc5e49f40f8fca3365c4f2#file-rr-service-selector-L46) you posted:

```
DEBU[0000] created scoped scope                          new=rexray parentScopes=rexray.modules.default-docker,
```

Note the your logs show the `rexray.modules.default-docker` scope is still being included. Thus the `-s|--service` switch will *never* be respected since there is a more specific property that defines `libstorage.service` nested under `rexray.modules.default-docker`.

Please remember to read the Slack channel as well as I wasted 90 minutes trying to replicate this before realizing you posted the same issue I already outlined and [fixed](https://github.com/akutz/rexray/commit/4d2694a61c3a701d0e665db7c4cd875cdefb84e9) earlier this evening.

**Comment by clintonskitson** [comment]
My fault @akutz. Tests good!

**Comment by akutz** [comment]
Hi @clintonskitson,

Not about blame (which is why I edited the above response to make sure I wasn't too harsh). It was late, I spent 90 minutes debugging when I wanted to play video games before bed :) I'm just glad you verified it worked. That's all I ultimately cared about.
