### ISSUE TITLE
States of deployment and installation

### ISSUE THREAD

**Issue by kacole2** [emccode/rexray#49]
I am building REX-Ray deployment into Docker Machine. In this case I will be doing it across multiple types of OSs.

This is going at a fast pace, so as of today, what's the best route to install REXray? from Bintray? from github releases? Is it going to be a `tar.gz` file or will it be the binary?

What is the long term approach going to be?

Would it be best to have a "latest" tag so the latest version is always pulled?

**Comment by akutz** [comment]
Hi @kacole2,

There will be no `latest` tag for the sources as it's easy enough to do this by pulling the tip. If you want the `latest` release that's possible with Bintray (see the badge at the top of the [RR readme](https://github.com/emccode/rexray) or go to this [link](https://bintray.com/akutz/generic/rexray/_latestVersion#files)), RPM, and Deb package managers as is. If you want latest for GH Releases, I will explore reintroducing that later, but until I remove all tags prior to `0.2.0-rc` I will not entertain it because I need to ensure all annotated tags follow a convention as they're used in the CI process. We will be able to use a non-annotated tag for `latest` on GH releases, but I'm not sure we need to do that either.

Here is the long-term approach - the CI process on Travis-CI builds *all* commits to master and uploads all artifacts to Bintray. All artifacts includes tarballs of the binaries and RPMs and DEBs (once @drumulonimbus integrates his work with the Makefile). 

The same CI process on Travis-CI will also upload the same artifacts to GH Releases but only for *tagged releases.* This way we can have all commits to master produce downloadable binaries for people who care about the latest, prebuilt release and store those binaries on a system which can handle them. Yet we can also have the official, released binaries duplexed up to GH releases when tags occur.

And again, the same CI process will upload the released RPM and DEB packages to the appropriate Bintray locations once @drumulonimbus integrates his work, provides the location, and I smooth out the integration.

As for how you wish to get the latest release -- pick your poison. The badge on the README will point to Bintray for now as it has the latest, pre-built binaries, but going forward see above.

**Comment by kacole2** [comment]
Ok. Long story short, always use the files on bintray?

**Comment by akutz** [comment]
Hi @kacole2,

I prefer not to simplify things to the point of reducing them past their point of value, but if you wish to look at it like that for now, sure. It's certainly fine until the documentation catches up.

**Comment by kacole2** [comment]
Here's my "rock and a hard place". I'm going to submit a PR to Docker Machine this week. This includes installing rexray. That's why I'm looking for today's approach and tomorrow's. Everything is very confusing because there are a bunch of different sources

**Comment by akutz** [comment]
Hi @kacole2,

It's not that confusing, I explained it above :) Please lay out your use case explicitly instead of attempting to understand a situation you yourself describe as fluid. I'll do my best to help come up with the best path forward for you *now*, but one that will also be sustainable moving forward. As you know, none of this was in place until recently, so it's in a moving state. That doesn't mean, however, that I won't try my hardest to accommodate you.

**Comment by kacole2** [comment]
This all goes back to the question I've been asking since we've met... What's the way we will "prefer" users to install rexray?

Docker-machine will install rexray on a number of different OSs. 

So do I download a tar.gz file? Download a bin file? Where is that file located? GitHub? Bintray? 

I know you're going to say that this is documented already but it seems like I am asking this every week. Sorry in advance.

**Comment by akutz** [comment]
Hi @kacole2,

This doesn't answer the question about the use case; it's still a vague, exploratory position. Users may install `REX-Ray` one way, but integrators such as yourself may prefer to integrate into a workflow another, see what I mean? 

If you want to keep it super simple then please see @drumulonimbus to make sure he works with me to get `REX-Ray`'s RPMs and DEBs hooked into CI process by when you need it, and then you'll just ask users to type `yum install rexray` or `apt-get install rexray`.

**Comment by kacole2** [comment]
My use case is installing rexray as an automated process during Docker Machine deployments of VMs. 

Just look at it as if I have a Linux box, and now I need to install rexray.

Are apt-get and yum available right now? I need to submit a PR this week. If not, then do I download the files directly from bintray?

I'm trying to make this super simple and not be complicated.

**Comment by akutz** [comment]
Hi @kacole2,

No, RPMs and DEBs are not available yet. @drumulonimbus is the man to ask -- once he gets his work complete and works with me to integrate it into the CI process so all binaries are built and blessed from a single environment, we'll start making those available.

**Comment by clintonskitson** [comment]
Question/statement here..

I am trying to think about the reason that we *should highly encourage and use* package management versus just installing binaries directly.  As @kacole2 is asking here, having a simple path that always resolves to the latest stable build is very much desired.

In the case of `Docker Machine`, the install would be happening against fresh OSs every time.  I can see package management as being useful here during the lifecycle or updates of the machine deployed (if there is one more than temporal usage).  

I kind of like the idea of possibly having the same steps to install RR across both Ubuntu/CentOS since RR does the service installs irrespective of OS.  Embedding the service installs in RR did open the door for us to minimize reliance on package managers.  Am I missing something here @akutz?

**Comment by akutz** [comment]
Hi @clintonskitson / @kacole2,

I honestly don't care how things are installed, and I believe everyone is just blowing everything out of proportion due to getting too excited about documentation that doesn't yet exist but is coming. We're giving users flexibility in how they wish to install / manage things, and we should all be able to see that as a long-term value proposition and not get hung up on the fact that we're rapidly delivering new bits and if there is not yet a clear message on installation, know that it's on the docket and/or fork the repo and provide that documentation. I'm more than happy to accept any ideas and suggestions, but I'll be much more thrilled when they come alongside forked repos and pull requests.

Also, I hope you both see that I'm not against a simple path, and I didn't indicate as such. I just said that I cannot reinstitute the `latest` tag at this time until the CI process is better tested as tags are now fundamental to the process. I'm putting a lot of pieces into place, and if I need to slow things down to allow others catch their breaths, I'm more than happy to do so, so please let me know.

**Comment by akutz** [comment]
Hi @clintonskitson / @kacole2,

I did not mean to close this issue; I apologize. The mouse was on the button, and I accidentally clicked it instead of `Comment`.

**Comment by akutz** [comment]
Hi @clintonskitson,

Also, should we consider a focus on documentation? It seems like lack of it is really starting to be an issue for others, and I really do not wish create impediments.

**Comment by clintonskitson** [comment]
@akutz and @kacole2 

Yes, we are definitely pushing the envelope when it comes to making large changes while also delivering solutions around 0.2.  I have no doubt that we will have things documented as they become finalized.

What was trying to be expressed in this thread was a need for solution to install RR that won't change so it can be embedded in a PR to Docker.  I believe the answer here is ensure the location and method of the binaries are out of the PR.  

Docker does this well.. `curl -sSL https://get.docker.com | sh -`.  So if we had a domain with a simple sh file returned, we would ultimate flexibility versus embedding binary downloads or package management steps.

@kacole2 I will own this and get you a solution soon.

**Comment by akutz** [comment]
Hi @clintonskitson,

Nor should we falsely hurry and do the wrong thing for people on different schedules than us. @drumulonimbus was adamantly against the notion of an analogue to what Docker does with a `curl` bit or else I would have done it. You did not express support for it then, so I assumed you did not care. If you would like that to happen, then let's file an issue and prioritize it or as you said, open a PR. Still, as the stewards of the project we have to consider the larger impact of small decisions now, and we must not let ourselves be steered into problematic areas with every issue that arises. I'm not saying this isn't important, but I am saying that we need to discuss it beyond the measure of a single need and how it will impact other aspects of the project and its roadmap.

**Comment by akutz** [comment]
Hi @clintonskitson,

By the way, thank you for finally expressing the ask in a concise manner. FWIW, I'm not sure we're ready to provide a way to install RR yet that will not change. At least not in the timeframe for which @kacole2 requires it. This is the first I'm hearing of this requirement, and as it's only a week out, it's a bit of a crunch to provide something indelible, especially as I'm working on the overall CI process as it is.

**Comment by akutz** [comment]
Hi @clintonskitson / @kacole2,

FYI, GitHub supports the `latest` release URL for all repositories even without the `latest` tag. The reason we don't have that option on `REX-Ray` is because we've not actually pushed a release yet. Everything is pre-release. And this is honestly the way it should be. @kacole2's code shouldn't pull down a pre-release version using the `latest` URL, it should pull the last, stable release.

**Comment by clintonskitson** [comment]
Got it @akutz, thanks.
