### ISSUE TITLE
Wrong package ?

### ISSUE THREAD

**Issue by ariksa** [emccode/rexray#68]
In ```storage/xtremio/storage.go``` the package is declared as ```package scaleio```.
Shouldn't it be ```package xtremio``` ?

**Comment by akutz** [comment]
Hi @ariksa,

Yes, but funny enough, it won't matter :) Since nothing references either package but those packages in fact register themselves with a manager in their `init` methods, this mistake has no side-effects other than being a truly stupid typo by yours truly.

@clintonskitson, do you concur? Obviously we should fix it, but I wouldn't think it's a `SEV-1` or anything...

**Comment by akutz** [comment]
Hi @clintonskitson,

I take that back, it turns out while it's a silly typo, it wasn't mine...this time :)

https://github.com/emccode/rexray/blame/master/storage/xtremio/storage.go

![image](https://cloud.githubusercontent.com/assets/101085/9982531/800c90d8-5fa5-11e5-987f-c0ef65d63ea1.png)

I only bring this up to note that it's been this way since June 4th (31d7859eb7), so I doubt it's truly causing any errors.

**Comment by clintonskitson** [comment]
Thanks for catching this @ariksa, PR here https://github.com/emccode/rexray/pull/70

**Comment by akutz** [comment]
The PR (#70) was merged with 0.2.0RC4
