### ISSUE TITLE
--Config parameter seems to be ignored

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#93]
It looks like this parameter is being ignored currently.

```
[root@mdm2 rexray]# mv /etc/rexray/config.yml /etc/rexray/config.yml-old
[root@mdm2 rexray]# rexray --config=/etc/rexray/config.yml-old volume
FATA[0000] Error: Driver Volume discovery failed: AWS was not able to validate the provided access credentials (AuthFailure) 
[root@mdm2 rexray]# mv /etc/rexray/config.yml-old /etc/rexray/config.yml
[root@mdm2 rexray]# rexray --config=/etc/rexray/config.yml-old volume
- name: ""
  volumeid: vol-5e0144a7
  availabilityzone: us-west-1b
  status: available
  volumetype: standard
  iops: 0
  size: "8"
  networkname: ""
  attachments: []
- name: ""
  volumeid: vol-4d0045b4
  availabilityzone: us-west-1b
  status: available
  volumetype: standard
  iops: 0

```

**Comment by akutz** [comment]
Hi @clintonskitson,

This should have been a quick fix, but I uncovered another bug. This one I call a Viper bug, but since I can work around it, and we're so close to release, I will. To replicate it set an environment variable for the log level or os drivers and then create a config file in your home directory. The config files are completely blowing away existing data. The way Viper reads in the files apparently completely nukes the existing config instead of overwriting non-empty values (which is what I expect). I can fix it on my end.
